---
title: "Data Exploration"
author: "Nathan Shepherd"
date: "`r Sys.Date()`"
output:
  pdf_document: default
---

```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(FactoMineR) # PCA
```

```{r}
rand_dat <- read_csv("../utils/rand_state_acts.csv",show_col_types = FALSE)
names(rand_dat)
```

```{r}
summary(rand_dat)
pairs(rand_dat[9:12])
```

```{r}
by_timestep = rand_dat %>% group_by(timestep)
timestep_summ = summarize(by_timestep, count=n(), avg.reward=mean(reward))
ggplot(timestep_summ, aes(x=timestep, y=count)) + geom_point()
```



```{r}
# Determine obs_axis with greatest difference for observation given the action
states = rand_dat %>% select(obs_ax0,obs_ax1,obs_ax2,obs_ax3,act)
sact0 = states %>% filter(act==0) %>% scale() %>% colMeans(na.rm = TRUE)
sact1 = states %>% filter(act==1) %>% scale() %>% colMeans(na.rm = TRUE)

sact0 - sact1
barplot(sact0 - sact1)
```

## Exploratory Factor Analysis

```{r}
# Maximum Likelihood Factor Analysis
# entering raw data and extracting 3 factors,
# with varimax rotation
mydata = states[1:4] # drop act
fit <- factanal(mydata, 1, rotation="varimax")
print(fit, digits=2, cutoff=.3, sort=TRUE)

# plot factor 1 by factor 2
#load <- fit$loadings[,1:2]
#plot(load,type="n") # set up plot
#text(load,labels=names(mydata),cex=.7) # add variable names
```
```{r}
# fraction of the variable’s total variance explained by the factor
apply(fit$loadings^2, 1, sum)
```
```{r}
Lambda <- fit$loadings
Psi <- diag(fit$uniquenesses)
S <- fit$correlation
Sigma <- Lambda %*% t(Lambda) + Psi
# residual matrix. Numbers close to 0 indicate that our factor model is a good representation of the underlying concept.
round(S - Sigma, 6)
```
```{r}
reg_fit <- factanal(mydata, factors = 1, scores = "regression")
mean(reg_fit$scores)
sd(reg_fit$scores)
```
```{r}
reg_fit$loadings
```
```{r}
ggplot(states, aes(obs_ax0)) + geom_density()
ggplot(states, aes(obs_ax1)) + geom_density()
ggplot(states, aes(obs_ax2)) + geom_density()
ggplot(states, aes(obs_ax3)) + geom_density()
```
```{r}
data_factor = data.frame(as.matrix(mydata) %*% matrix(fit$loadings))
names(data_factor) = c("fact")
ggplot(data_factor, aes(fact)) + geom_density()
```
```{r}
# PCA Variable Factor Map
# NOTE: scaling has no effect on fit
data_factor$act = states$act
res <- PCA(data_factor)
```

```{r}
result <- PCA(mydata) # graphs generated automatically
```

```{r}
result <- PCA(states) # graphs generated automatically
```

