---
title: "Predict States"
author: "Nathan Shepherd"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r}
library(readr)
library(dplyr)
library(ggplot2)
```

```{r}
rand_state_acts <- read_csv("../utils/rand_state_acts.csv")
names(rand_state_acts)
```

```{r}
# Roughly 50% of actions should be left
summary(rand_state_acts$act)
#pairs(rand_state_acts[5:12])
```

```{r}
ggplot(rand_state_acts, aes(x=timestep, y=obs_ax0)) +
  geom_point(aes(colour=episode))

ggplot(filter(rand_state_acts, reward>mean(reward)),
  aes(x=timestep, y=obs_ax0, colour=episode, shape=factor(act))) +
  geom_point()

ggplot(filter(rand_state_acts, 
              reward>mean(reward) & episode>35),
  aes(x=timestep, y=obs_ax0,
      shape=factor(episode),
      colour=factor(act))) +
  geom_point()
#binaxis = "x", binwidth = .01
```

```{r}
ax0_pred = lm(obs_ax0 ~ next_ax0 + factor(act), data=rand_state_acts)
#summary(ax0_pred) 

ax1_pred = lm(obs_ax1 ~ next_ax1 + factor(act), data=rand_state_acts)
summary(ax1_pred) # Act is a significant predictor here

ax2_pred = lm(obs_ax2 ~ next_ax2 + factor(act), data=rand_state_acts)
#summary(ax2_pred)

ax3_pred = lm(obs_ax3 ~ next_ax3 + factor(act), data=rand_state_acts)
summary(ax3_pred) # Act is a significant predictor here
```

```{r}
states = data.frame(ax0=rand_state_acts$obs_ax0,
                    ax1=rand_state_acts$obs_ax1,
                    ax2=rand_state_acts$obs_ax2,
                    ax3=rand_state_acts$obs_ax3)
s_next = data.frame(ax0=rand_state_acts$next_ax0,
                    ax1=rand_state_acts$next_ax1,
                    ax2=rand_state_acts$next_ax2,
                    ax3=rand_state_acts$next_ax3)
fit <- factanal(states, 1, rotation="varimax")
states_factor = as.matrix(states) %*% matrix(fit$loadings)
s_next_factor = as.matrix(s_next) %*% matrix(fit$loadings)
factor_predict = lm(s_next_factor ~ states_factor + factor(rand_state_acts$act))
summary(factor_predict)
```
```{r}
fit$loadings
```

